const books = [
    { title: "Crime and Punishment", author: "Fyodor Dostoyevsky" },
    { title: "Anna Karenina", author: "Leo Tolstoy" },
    { title: "The Brothers Karamazov", author: "Fyodor Dostoyevsky" },
    { title: "War and Peace", author: "Leo Tolstoy" },
    { title: "The Idiot", author: "Fyodor Dostoyevsky" },
    { title: "Fathers and Sons", author: "Ivan Turgenev" },
    { title: "Dead Souls", author: "Nikolai Gogol" },
    { title: "The Master and Margarita", author: "Mikhail Bulgakov" },
    { title: "The Death of Ivan Ilyich", author: "Leo Tolstoy" },
    { title: "Notes from Underground", author: "Fyodor Dostoyevsky" },
    { title: "The Metamorphosis", author: "Franz Kafka" },
    { title: "The Trial", author: "Franz Kafka" },
    { title: "The Castle", author: "Franz Kafka" },
    { title: "The Sorrows of Young Werther", author: "Johann Wolfgang von Goethe" },
    { title: "Faust", author: "Johann Wolfgang von Goethe" },
    { title: "Madame Bovary", author: "Gustave Flaubert" },
    { title: "Les Misérables", author: "Victor Hugo" },
    { title: "The Hunchback of Notre-Dame", author: "Victor Hugo" },
    { title: "Germinal", author: "Émile Zola" },
    { title: "Nana", author: "Émile Zola" },
    { title: "The Red and the Black", author: "Stendhal" },
    { title: "The Charterhouse of Parma", author: "Stendhal" },
    { title: "The Picture of Dorian Gray", author: "Oscar Wilde" },
    { title: "The Importance of Being Earnest", author: "Oscar Wilde" },
    { title: "Salomé", author: "Oscar Wilde" },
    { title: "To the Lighthouse", author: "Virginia Woolf" },
    { title: "Mrs Dalloway", author: "Virginia Woolf" },
    { title: "Orlando", author: "Virginia Woolf" },
    { title: "A Room of One’s Own", author: "Virginia Woolf" },
    { title: "The Waves", author: "Virginia Woolf" },
    { title: "Pride and Prejudice", author: "Jane Austen" },
    { title: "Sense and Sensibility", author: "Jane Austen" },
    { title: "The Stranger", author: "Albert Camus" },
    { title: "The Plague", author: "Albert Camus" },
    { title: "The Fall", author: "Albert Camus" },
    { title: "Thus Spoke Zarathustra", author: "Friedrich Nietzsche" },
    { title: "Beyond Good and Evil", author: "Friedrich Nietzsche" },
    { title: "On the Genealogy of Morals", author: "Friedrich Nietzsche" },
    { title: "The Magic Mountain", author: "Thomas Mann" },
    { title: "Death in Venice", author: "Thomas Mann" },
    { title: "Buddenbrooks", author: "Thomas Mann" },
    { title: "Doctor Faustus", author: "Thomas Mann" },
    { title: "Steppenwolf", author: "Hermann Hesse" },
    { title: "Siddhartha", author: "Hermann Hesse" },
    { title: "Demian", author: "Hermann Hesse" },
    { title: "Nausea", author: "Jean-Paul Sartre" },
    { title: "Being and Nothingness", author: "Jean-Paul Sartre" },
    { title: "The Age of Reason", author: "Jean-Paul Sartre" },
    { title: "In Search of Lost Time", author: "Marcel Proust" },
    { title: "Swann’s Way", author: "Marcel Proust" },
    { title: "The Guermantes Way", author: "Marcel Proust" },
    { title: "Journey to the End of the Night", author: "Louis-Ferdinand Céline" },
    { title: "Death on Credit", author: "Louis-Ferdinand Céline" },
    { title: "Candide", author: "Voltaire" },
    { title: "The Three Musketeers", author: "Alexandre Dumas" },
    { title: "The Count of Monte Cristo", author: "Alexandre Dumas" },
    { title: "The Leopard", author: "Giuseppe Tomasi di Lampedusa" },
    { title: "Gigi", author: "Colette" },
    { title: "Chéri", author: "Colette" },
    { title: "Journey to the Center of the Earth", author: "Jules Verne" },
    { title: "Twenty Thousand Leagues Under the Sea", author: "Jules Verne" },
    { title: "Around the World in Eighty Days", author: "Jules Verne" },
    { title: "The Possessed", author: "Fyodor Dostoyevsky" },
    { title: "A Hero of Our Time", author: "Mikhail Lermontov" },
    { title: "The Overcoat", author: "Nikolai Gogol" },
    { title: "The Seagull", author: "Anton Chekhov" },
    { title: "Uncle Vanya", author: "Anton Chekhov" },
    { title: "The Cherry Orchard", author: "Anton Chekhov" },
    { title: "Resurrection", author: "Leo Tolstoy" },
    { title: "The Kreutzer Sonata", author: "Leo Tolstoy" },
    { title: "Hadji Murat", author: "Leo Tolstoy" },
    { title: "The Gambler", author: "Fyodor Dostoyevsky" },
    { title: "The Double", author: "Fyodor Dostoyevsky" },
    { title: "White Nights", author: "Fyodor Dostoyevsky" },
    { title: "The Queen of Spades", author: "Alexander Pushkin" },
    { title: "Eugene Onegin", author: "Alexander Pushkin" },
    { title: "The Captain’s Daughter", author: "Alexander Pushkin" },
    { title: "Demons", author: "Fyodor Dostoyevsky" },
    { title: "The Trial of Socrates", author: "I.F. Stone" },
    { title: "The Man Without Qualities", author: "Robert Musil" },
    { title: "Berlin Alexanderplatz", author: "Alfred Döblin" },
    { title: "The Glass Bead Game", author: "Hermann Hesse" },
    { title: "Journey to the East", author: "Hermann Hesse" },
    { title: "Don Quixote", author: "Miguel de Cervantes" },
    { title: "The Sorrows of Young Werther", author: "Johann Wolfgang von Goethe" },
    { title: "Dr. Zhivago", author: "Boris Pasternak" },
    { title: "One Day in the Life of Ivan Denisovich", author: "Aleksandr Solzhenitsyn" },
    { title: "The First Circle", author: "Aleksandr Solzhenitsyn" },
];

module.exports = books;
