const books = [
    "Crime and Punishment - Fyodor Dostoyevsky",
    "Anna Karenina - Leo Tolstoy",
    "The Brothers Karamazov - Fyodor Dostoyevsky",
    "War and Peace - Leo Tolstoy",
    "The Metamorphosis - Franz Kafka",
    "The Trial - Franz Kafka",
    "Madame Bovary - Gustave Flaubert",
    "Les Misérables - Victor Hugo",
    "The Picture of Dorian Gray - Oscar Wilde",
    "To the Lighthouse - Virginia Woolf",
    "Mrs Dalloway - Virginia Woolf",
    "The Stranger - Albert Camus",
    "The Plague - Albert Camus",
    "Thus Spoke Zarathustra - Friedrich Nietzsche",
    "Faust - Johann Wolfgang von Goethe",
    "Steppenwolf - Hermann Hesse",
    "Siddhartha - Hermann Hesse",
    "Journey to the End of the Night - Louis-Ferdinand Céline",
    "The Count of Monte Cristo - Alexandre Dumas",
    "The Hunchback of Notre-Dame - Victor Hugo",
    "Fathers and Sons - Ivan Turgenev",
    "Dead Souls - Nikolai Gogol",
    "The Master and Margarita - Mikhail Bulgakov",
    "The Idiot - Fyodor Dostoyevsky",
    "Candide - Voltaire",
    "The Red and the Black - Stendhal",
    "Swann's Way - Marcel Proust",
    "The Sorrows of Young Werther - Johann Wolfgang von Goethe",
    "In Search of Lost Time - Marcel Proust",
    "The Magic Mountain - Thomas Mann",
    "Demian - Hermann Hesse",
    "Nausea - Jean-Paul Sartre",
    "The Age of Reason - Jean-Paul Sartre",
    "The Charterhouse of Parma - Stendhal",
    "Journey to the Center of the Earth - Jules Verne",
    "Twenty Thousand Leagues Under the Sea - Jules Verne",
    "Around the World in Eighty Days - Jules Verne",
    "The Glass Bead Game - Hermann Hesse",
    "Doctor Faustus - Thomas Mann",
    "Buddenbrooks - Thomas Mann",
    "Berlin Alexanderplatz - Alfred Döblin",
    "The Man Without Qualities - Robert Musil",
    "The Overcoat - Nikolai Gogol",
    "Resurrection - Leo Tolstoy",
    "Hadji Murat - Leo Tolstoy",
    "The Seagull - Anton Chekhov",
    "Uncle Vanya - Anton Chekhov",
    "The Cherry Orchard - Anton Chekhov"
];

module.exports = books;
